# Generated by Django 2.0.3 on 2018-03-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0003_accreditatonapplication_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditatonapplication',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
