# Generated by Django 2.0.3 on 2018-03-12 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0005_auto_20180312_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditatonapplication',
            name='applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
