# Generated by Django 2.0.3 on 2018-03-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0007_accreditatonapplication_type_of_accreditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditatonapplication',
            name='type_of_accreditation',
            field=models.CharField(choices=[('photo', 'Photo Pass'), ('jounalist', 'Journalist Pass'), ('festival', 'Festival Pass')], default=None, max_length=9),
        ),
    ]
