# Generated by Django 2.0.3 on 2018-03-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0008_auto_20180312_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accreditatonapplication',
            old_name='reviewed',
            new_name='granted',
        ),
    ]
