# Generated by Django 2.0.3 on 2018-03-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0010_accreditatonapplication_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditatonapplication',
            name='discount_amount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='accreditatonapplication',
            name='discount_code',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
