# Generated by Django 2.0.3 on 2018-03-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation_app', '0011_auto_20180313_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditatonapplication',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('A', 'Photo Pass A'), ('B', 'Photo Pass B'), ('C', 'Photo Pass C')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='accreditatonapplication',
            name='discount_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accreditatonapplication',
            name='discount_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
